class CommonKeys:
    # FLIGHT
    YEAR = "Year"
    MONTH = "Month"
    DAY_OF_MONTH = "DayOfMonth"
    DAY_OF_WEEK = "DayOfWeek"
    DEPARTURE_TIME = "DepTime"
    SCHEDULE_DEPARTURE_TIME = "CRSDepTime"
    ARRIVAL_TIME = "ArrTime"
    SCHEDULE_ARRIVAL_TIME = "CRSArrTime"
    UNIQUE_CARRIER = "UniqueCarrier"
    FLIGHT_NUM = "FlightNum"
    TAIL_NUM = "TailNum"
    ACTUAL_ELAPSED_TIME = "ActualElapsedTime"
    SCHEDULE_ELAPSED_TIME = "CRSElapsedTime"
    AIR_TIME = "AirTime"
    ARRIVAL_DELAY = "ArrDelay"
    DEPARTURE_DELAY = "DepDelay"
    ORIGIN = "Origin"
    DESTINATION = "Dest"
    DISTANCE = "Distance"
    TAXI_IN = "TaxiIn"
    TAXI_OUT = "TaxiOut"
    CANCELLED = "Cancelled"
    CANCELLATION_CODE = "CancellationCode"
    DIVERTED = "Diverted"
    CARRIER_DELAY = "CarrierDelay"
    WEATHER_DELAY = "WeatherDelay"
    NAS_DELAY = "NASDelay"
    SECURITY_DELAY = "SecurityDelay"
    LATE_AIRCRAFT_DELAY = "LateAircraftDelay"

    # AIRPORT
    IATA = "iata"
    AIRPORT = "airport"
    CITY = "city"
    STATE = "state"
    COUNTRY = "country"
    LAT = "lat"
    LON = "long"

    # CARRIER
    CODE = "Code"
    DESCRIPTION = "Description"

    # PLANE
    TYPE = "type"
    MANUFACTURER = "manufacturer"
    ISSUE_DATE = "issue_date"
    MODEL = "model"
    STATUS = "status"
    AIRCRAFT_TYPE = "aircraft_type"
    ENGINE_TYPE = "engine_type"
    PLANE_TAIL_NUM = "tailnum"
    PLANE_YEAR = "year"

    # COMMON
    TOTAL = "total"
    DELAY_COUNT = "delay_count"
